import {
  ListChecks, Leaf, Droplets, Sparkles, Wallet, Brain,
} from 'lucide-react';

export const CORNERS = {
  tasks: {
    id: 'tasks',
    name: 'My Tasks',
    emoji: '✅',
    icon: ListChecks,
    description: 'Your daily goals & to-dos',
    primary: '#18181b',
    soft: '#f4f4f5',
    border: '#d4d4d8',
    ring: 'rgba(24,24,27,0.25)',
    badge: { bg: '#f4f4f5', text: '#18181b' },
    gradient: 'linear-gradient(135deg,#f4f4f5 0%,#e4e4e7 100%)',
    btnGradient: 'linear-gradient(135deg,#18181b,#3f3f46)',
    tips: [],
  },
  healthy: {
    id: 'healthy',
    name: 'Healthy Corner',
    emoji: '🥗',
    icon: Leaf,
    description: 'Nourish your body & build habits',
    primary: '#16a34a',
    soft: '#f0fdf4',
    border: '#bbf7d0',
    ring: 'rgba(22,163,74,0.2)',
    badge: { bg: '#dcfce7', text: '#15803d' },
    gradient: 'linear-gradient(135deg,#f0fdf4 0%,#dcfce7 100%)',
    btnGradient: 'linear-gradient(135deg,#22c55e,#16a34a)',
    tips: [
      { icon: '💧', text: 'Drink 8 glasses of water daily to stay energized.' },
      { icon: '🥦', text: 'Fill half your plate with vegetables at every meal.' },
      { icon: '🚶', text: 'A 20-minute walk after meals boosts digestion by 30%.' },
      { icon: '😴', text: '7-9 hours of sleep is when your body repairs itself.' },
      { icon: '🍳', text: 'Meal prepping on Sundays saves time and money all week.' },
    ],
  },
  skin: {
    id: 'skin',
    name: 'Skin Corner',
    emoji: '💧',
    icon: Droplets,
    description: 'Glow from the outside in',
    primary: '#0ea5e9',
    soft: '#f0f9ff',
    border: '#bae6fd',
    ring: 'rgba(14,165,233,0.2)',
    badge: { bg: '#e0f2fe', text: '#0369a1' },
    gradient: 'linear-gradient(135deg,#f0f9ff 0%,#e0f2fe 100%)',
    btnGradient: 'linear-gradient(135deg,#38bdf8,#0ea5e9)',
    tips: [
      { icon: '🧴', text: 'Always apply SPF 30+ sunscreen — even on cloudy days.' },
      { icon: '💦', text: 'Double cleanse at night to remove makeup and SPF fully.' },
      { icon: '🌙', text: 'Use retinol at night only — it breaks down in sunlight.' },
      { icon: '🥤', text: 'Hydrated skin starts from within — drink your water!' },
      { icon: '🛏️', text: 'Change your pillowcase twice a week to prevent breakouts.' },
    ],
  },
  glowup: {
    id: 'glowup',
    name: 'Glow Up',
    emoji: '✨',
    icon: Sparkles,
    description: 'Become your best self',
    primary: '#7c3aed',
    soft: '#f5f3ff',
    border: '#ddd6fe',
    ring: 'rgba(124,58,237,0.2)',
    badge: { bg: '#ede9fe', text: '#6d28d9' },
    gradient: 'linear-gradient(135deg,#f5f3ff 0%,#ede9fe 100%)',
    btnGradient: 'linear-gradient(135deg,#8b5cf6,#7c3aed)',
    tips: [
      { icon: '📖', text: 'Read 10 pages a day — that\'s 12+ books a year.' },
      { icon: '🪞', text: 'Dress for who you\'re becoming, not who you were.' },
      { icon: '🏋️', text: 'Consistency beats perfection every single time.' },
      { icon: '📵', text: 'First 30 minutes after waking: no phone. Set the tone.' },
      { icon: '🎯', text: 'Write down 3 things you want to achieve this week.' },
    ],
  },
  financial: {
    id: 'financial',
    name: 'Financial',
    emoji: '💰',
    icon: Wallet,
    description: 'Spend wisely, save smartly',
    primary: '#d97706',
    soft: '#fffbeb',
    border: '#fde68a',
    ring: 'rgba(217,119,6,0.2)',
    badge: { bg: '#fef3c7', text: '#b45309' },
    gradient: 'linear-gradient(135deg,#fffbeb 0%,#fef3c7 100%)',
    btnGradient: 'linear-gradient(135deg,#f59e0b,#d97706)',
    tips: [
      { icon: '💳', text: 'Follow the 50/30/20 rule: needs, wants, savings.' },
      { icon: '☕', text: 'Track every purchase for 30 days — awareness is power.' },
      { icon: '🛒', text: 'Shop with a list and a 24-hour rule on non-essentials.' },
      { icon: '📈', text: 'Automate savings — pay yourself before you spend.' },
      { icon: '🎁', text: 'Set a monthly "fun budget" so you don\'t feel deprived.' },
    ],
  },
  mind: {
    id: 'mind',
    name: 'Mind & Soul',
    emoji: '🧘',
    icon: Brain,
    description: 'Peace, growth & inner calm',
    primary: '#0d9488',
    soft: '#f0fdfa',
    border: '#99f6e4',
    ring: 'rgba(13,148,136,0.2)',
    badge: { bg: '#ccfbf1', text: '#0f766e' },
    gradient: 'linear-gradient(135deg,#f0fdfa 0%,#ccfbf1 100%)',
    btnGradient: 'linear-gradient(135deg,#2dd4bf,#0d9488)',
    tips: [
      { icon: '🧘', text: 'Five deep breaths can lower cortisol by up to 20%.' },
      { icon: '📓', text: 'Write 3 gratitudes each morning to rewire your mindset.' },
      { icon: '🌿', text: 'Spend 20 minutes outdoors daily — nature heals the mind.' },
      { icon: '🤝', text: 'Set boundaries with kindness — your energy is sacred.' },
      { icon: '📵', text: 'A digital detox one day a week restores mental clarity.' },
    ],
  },
};

export const CORNER_ORDER = ['tasks', 'healthy', 'skin', 'glowup', 'financial', 'mind'];

/** Build a full corner config object from a DB user_corner row */
export function makeCustomCorner(row) {
  const hex = row.color || '#6366f1';
  const [r, g, b] = [
    parseInt(hex.slice(1, 3), 16),
    parseInt(hex.slice(3, 5), 16),
    parseInt(hex.slice(5, 7), 16),
  ];
  return {
    id: `c_${row.id}`,
    name: row.name,
    emoji: row.emoji || '📌',
    icon: null,               // no lucide icon for custom corners
    description: 'My custom corner',
    primary:     hex,
    soft:        `rgba(${r},${g},${b},0.08)`,
    border:      `rgba(${r},${g},${b},0.22)`,
    ring:        `rgba(${r},${g},${b},0.25)`,
    badge:       { bg: `rgba(${r},${g},${b},0.1)`, text: hex },
    gradient:    `linear-gradient(135deg,rgba(${r},${g},${b},0.08) 0%,rgba(${r},${g},${b},0.04) 100%)`,
    btnGradient: `linear-gradient(135deg,${hex},rgba(${r},${g},${b},0.75))`,
    tips: [],
    isCustom: true,
    dbId: row.id,
  };
}
